version: "3.8"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-pmysql",  "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./server
    environment:
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: mysql
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  app-data:
