version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME:-db}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-u${DB_USER:-user}",
          "-p${DB_PASSWORD:-mysql}",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DB_NAME:-db}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-mysql}
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  mysql-data:
  app-data:
